services:
  - type: web
    name: employee-management-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://trphuong1305:zwHoIEJ1Yh1iP6Ok@cluster0-funa.ai2tq.mongodb.net/funa?retryWrites=true&w=majority
      - key: PORT
        value: 5000
      - key: ACCESS_TOKEN_SECRET
        value: access_token_secret_key_for_employee_management_system
      - key: REFRESH_TOKEN_SECRET
        value: refresh_token_secret_key_for_employee_management_system
      - key: CLIENT_URL
        value: https://employeesmanage-a807d.web.app
